// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/tours/tours.proto

package tours

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToursService_GetTours_FullMethodName           = "/tours.ToursService/GetTours"
	ToursService_GetKeyPointsByTour_FullMethodName = "/tours.ToursService/GetKeyPointsByTour"
)

// ToursServiceClient is the client API for ToursService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tours servis
type ToursServiceClient interface {
	GetTours(ctx context.Context, in *GetToursRequest, opts ...grpc.CallOption) (*GetToursResponse, error)
	GetKeyPointsByTour(ctx context.Context, in *GetKeyPointsByTourRequest, opts ...grpc.CallOption) (*GetKeyPointsByTourResponse, error)
}

type toursServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToursServiceClient(cc grpc.ClientConnInterface) ToursServiceClient {
	return &toursServiceClient{cc}
}

func (c *toursServiceClient) GetTours(ctx context.Context, in *GetToursRequest, opts ...grpc.CallOption) (*GetToursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToursResponse)
	err := c.cc.Invoke(ctx, ToursService_GetTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetKeyPointsByTour(ctx context.Context, in *GetKeyPointsByTourRequest, opts ...grpc.CallOption) (*GetKeyPointsByTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPointsByTourResponse)
	err := c.cc.Invoke(ctx, ToursService_GetKeyPointsByTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToursServiceServer is the server API for ToursService service.
// All implementations must embed UnimplementedToursServiceServer
// for forward compatibility.
//
// Tours servis
type ToursServiceServer interface {
	GetTours(context.Context, *GetToursRequest) (*GetToursResponse, error)
	GetKeyPointsByTour(context.Context, *GetKeyPointsByTourRequest) (*GetKeyPointsByTourResponse, error)
	mustEmbedUnimplementedToursServiceServer()
}

// UnimplementedToursServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToursServiceServer struct{}

func (UnimplementedToursServiceServer) GetTours(context.Context, *GetToursRequest) (*GetToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTours not implemented")
}
func (UnimplementedToursServiceServer) GetKeyPointsByTour(context.Context, *GetKeyPointsByTourRequest) (*GetKeyPointsByTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointsByTour not implemented")
}
func (UnimplementedToursServiceServer) mustEmbedUnimplementedToursServiceServer() {}
func (UnimplementedToursServiceServer) testEmbeddedByValue()                      {}

// UnsafeToursServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToursServiceServer will
// result in compilation errors.
type UnsafeToursServiceServer interface {
	mustEmbedUnimplementedToursServiceServer()
}

func RegisterToursServiceServer(s grpc.ServiceRegistrar, srv ToursServiceServer) {
	// If the following call pancis, it indicates UnimplementedToursServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToursService_ServiceDesc, srv)
}

func _ToursService_GetTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetTours(ctx, req.(*GetToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetKeyPointsByTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointsByTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetKeyPointsByTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetKeyPointsByTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetKeyPointsByTour(ctx, req.(*GetKeyPointsByTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToursService_ServiceDesc is the grpc.ServiceDesc for ToursService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToursService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.ToursService",
	HandlerType: (*ToursServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTours",
			Handler:    _ToursService_GetTours_Handler,
		},
		{
			MethodName: "GetKeyPointsByTour",
			Handler:    _ToursService_GetKeyPointsByTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tours/tours.proto",
}
