// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/balance/balance.proto

package balance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_balance_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_balance_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_balance_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_balance_balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceRequest) Reset() {
	*x = AddBalanceRequest{}
	mi := &file_proto_balance_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceRequest) ProtoMessage() {}

func (x *AddBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceRequest.ProtoReflect.Descriptor instead.
func (*AddBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_balance_balance_proto_rawDescGZIP(), []int{2}
}

func (x *AddBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBalance    float64                `protobuf:"fixed64,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceResponse) Reset() {
	*x = AddBalanceResponse{}
	mi := &file_proto_balance_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceResponse) ProtoMessage() {}

func (x *AddBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceResponse.ProtoReflect.Descriptor instead.
func (*AddBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_balance_balance_proto_rawDescGZIP(), []int{3}
}

func (x *AddBalanceResponse) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *AddBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeductBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceRequest) Reset() {
	*x = DeductBalanceRequest{}
	mi := &file_proto_balance_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceRequest) ProtoMessage() {}

func (x *DeductBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceRequest.ProtoReflect.Descriptor instead.
func (*DeductBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_balance_balance_proto_rawDescGZIP(), []int{4}
}

func (x *DeductBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeductBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBalance    float64                `protobuf:"fixed64,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceResponse) Reset() {
	*x = DeductBalanceResponse{}
	mi := &file_proto_balance_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceResponse) ProtoMessage() {}

func (x *DeductBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceResponse.ProtoReflect.Descriptor instead.
func (*DeductBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_balance_balance_proto_rawDescGZIP(), []int{5}
}

func (x *DeductBalanceResponse) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *DeductBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_balance_balance_proto protoreflect.FileDescriptor

const file_proto_balance_balance_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/balance/balance.proto\x12\abalance\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"b\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"D\n" +
	"\x11AddBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"i\n" +
	"\x12AddBalanceResponse\x12\x1f\n" +
	"\vnew_balance\x18\x01 \x01(\x01R\n" +
	"newBalance\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"G\n" +
	"\x14DeductBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"l\n" +
	"\x15DeductBalanceResponse\x12\x1f\n" +
	"\vnew_balance\x18\x01 \x01(\x01R\n" +
	"newBalance\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf4\x01\n" +
	"\x0eBalanceService\x12G\n" +
	"\n" +
	"GetBalance\x12\x1a.balance.GetBalanceRequest\x1a\x1b.balance.GetBalanceResponse\"\x00\x12G\n" +
	"\n" +
	"AddBalance\x12\x1a.balance.AddBalanceRequest\x1a\x1b.balance.AddBalanceResponse\"\x00\x12P\n" +
	"\rDeductBalance\x12\x1d.balance.DeductBalanceRequest\x1a\x1e.balance.DeductBalanceResponse\"\x00B\x11Z\x0f./proto/balanceb\x06proto3"

var (
	file_proto_balance_balance_proto_rawDescOnce sync.Once
	file_proto_balance_balance_proto_rawDescData []byte
)

func file_proto_balance_balance_proto_rawDescGZIP() []byte {
	file_proto_balance_balance_proto_rawDescOnce.Do(func() {
		file_proto_balance_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_balance_balance_proto_rawDesc), len(file_proto_balance_balance_proto_rawDesc)))
	})
	return file_proto_balance_balance_proto_rawDescData
}

var file_proto_balance_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_balance_balance_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),     // 0: balance.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 1: balance.GetBalanceResponse
	(*AddBalanceRequest)(nil),     // 2: balance.AddBalanceRequest
	(*AddBalanceResponse)(nil),    // 3: balance.AddBalanceResponse
	(*DeductBalanceRequest)(nil),  // 4: balance.DeductBalanceRequest
	(*DeductBalanceResponse)(nil), // 5: balance.DeductBalanceResponse
}
var file_proto_balance_balance_proto_depIdxs = []int32{
	0, // 0: balance.BalanceService.GetBalance:input_type -> balance.GetBalanceRequest
	2, // 1: balance.BalanceService.AddBalance:input_type -> balance.AddBalanceRequest
	4, // 2: balance.BalanceService.DeductBalance:input_type -> balance.DeductBalanceRequest
	1, // 3: balance.BalanceService.GetBalance:output_type -> balance.GetBalanceResponse
	3, // 4: balance.BalanceService.AddBalance:output_type -> balance.AddBalanceResponse
	5, // 5: balance.BalanceService.DeductBalance:output_type -> balance.DeductBalanceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_balance_balance_proto_init() }
func file_proto_balance_balance_proto_init() {
	if File_proto_balance_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_balance_balance_proto_rawDesc), len(file_proto_balance_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_balance_balance_proto_goTypes,
		DependencyIndexes: file_proto_balance_balance_proto_depIdxs,
		MessageInfos:      file_proto_balance_balance_proto_msgTypes,
	}.Build()
	File_proto_balance_balance_proto = out.File
	file_proto_balance_balance_proto_goTypes = nil
	file_proto_balance_balance_proto_depIdxs = nil
}
